### ISSUE TITLE
와이어프레임 설계

### ISSUE THREAD

**Issue by ClszK** [42seoul-ft-transcendence/ft_transcendence#11]
## 원격 플레이어 모듈 필수?

와이어프레임을 설계하는 도중에 이 부분을 어떻게 해결해야할지 모르겠네요.

subject에서  Live Chat module에 다음과 같은 문구가 있습니다.
_◦ The user should be able to invite other users to play a Pong game through the chat interface._

원격 플레이어를 구현하지 않는 이상 채팅으로 상대방을 초대했지만 게임 시작을 할 수단이 없는거 같아요.

42gg에 있는 당구 게임처럼
"1 대 1하러 제 위치로 오세요"와 같은 방식으로 구현하면 해결할 수 있을텐데, 어떻게 생각하시나요?

**Comment by sumssumm** [comment]
https://www.figma.com/design/VR4PnQEcCHFVk0silvOQuC/ft_transcendence?node-id=19-59&node-type=frame&t=cUKdzuaITJ1HhN0o-0
와이어 프레임 입니다.
